apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: ngin
          image: nginx
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html

  volumeClaimTemplates:
    - metadata:
        name: nginx-html

      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1G
---
