apiVersion : v1
kind : Pod
metadata :
  name : java-app
  labels :
    app : java-app

spec :
  containers :
    - name : java-container
      image : iesodias/java-api:latest
      ports :
        - containerPort : 8081