FROM node:24.13 AS builder

WORKDIR /app

COPY src/package.json .

RUN npm install

COPY src/ .


FROM node:24.13-alpine AS runner

WORKDIR /app

COPY --from=builder /app .

EXPOSE 3000

CMD ["npm", "start"]