apiVersion: v1
kind: Pod
metadata:
  name: basic-pod
spec:
  containers:
    - name: basic-container
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Service
metadata:
  name: basic-service
spec:
  selector:
    app: basic-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
