GET http://localhost:8080/

###

GET http://localhost:8080/health

###

POST http://localhost:8080/

{
    "id": 1,
    "name": "mouse"
}

###

POST http://localhost:9000/realms/course/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=email&client_secret=IVyLO8LnOZFsGTlUUe5qgwb1ScbJ6X79&grant_type=client_credentials

###

POST http://localhost:9000/realms/course/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=email_users&username=nickolss&password=123&grant_type=password