name: deploy terraform to azure

on:
    workflow_dispatch:
        inputs:
            destroy:
                description: "Destroy infrastructure"
                required: false
                default: "false"

permissions:
    contents: read
    id-token: write

jobs:
    validate:
        if: ${{ github.event.inputs.destroy == 'false' }}
        name: Validate terraform
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Azure Login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Terraform Install
              uses: hashicorp/setup-terraform@v3

            - name: Terraform Validate
              working-directory: infra
              run: |
                  export ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}
                  terraform init
                  terraform fmt --check
                  terraform validate
                  terraform plan -out=tfplan
