apiVersion: v1
kind: Service
metadata:
  name: myheadless_service
spec:
  selector:
    app: nginx
  type: ClusterIP
  clusterIP: None
  ports:
    - name: myjob
      port: 80
      targetPort: 80
---
